// Automatically generated by ./configure 
#pragma once
#define ARCH "x86_64"
#define CPU "generic"
#define WITHOUT_OPTIMIZATION 0
#define WITH_JSON 1
#define MKL_APP_NAME "MKL_APP_NAME"
#define MKL_APP_DESC_ONELINE "MKL_APP_DESC_ONELINE"
// gcc
#define WITH_GCC 1
// pkgconfig
#define WITH_PKGCONFIG 1
// install
#define WITH_INSTALL 1
// gitversion
#define KAFKACAT_VERSION "1.3.1"
// librdkafka_ge_090
#define ENABLE_KAFKACONSUMER 1
